import * as Joi from 'joi';

export const envSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'test', 'production')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  API_PREFIX: Joi.string().default('api'),
  API_VERSION: Joi.string().default('1'),
  APP_NAME: Joi.string().default('PropFlow API'),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  DATABASE_URL: Joi.string().required(),
  JWT_ACCESS_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_TTL: Joi.number().default(3600),
  JWT_REFRESH_TTL: Joi.number().default(1209600),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().port().required(),
  REDIS_USERNAME: Joi.string().allow('').optional(),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_DB: Joi.number().default(0),
  THROTTLE_SHORT_TTL_MS: Joi.number().positive().default(10_000),
  THROTTLE_SHORT_LIMIT: Joi.number().positive().default(30),
  THROTTLE_MEDIUM_TTL_MS: Joi.number().positive().default(60_000),
  THROTTLE_MEDIUM_LIMIT: Joi.number().positive().default(120),
  THROTTLE_LONG_TTL_MS: Joi.number().positive().default(3_600_000),
  THROTTLE_LONG_LIMIT: Joi.number().positive().default(1000),
  AWS_REGION: Joi.string().required(),
  AWS_S3_BUCKET: Joi.string().required(),
  AWS_ACCESS_KEY_ID: Joi.string().required(),
  AWS_SECRET_ACCESS_KEY: Joi.string().required(),
  AWS_S3_ENDPOINT: Joi.string().allow('').optional(),
  AWS_S3_FORCE_PATH_STYLE: Joi.boolean().truthy('true').falsy('false').default(false),
  AWS_CLOUDFRONT_DOMAIN: Joi.string().allow('').optional(),
  AUDIT_LOG_ENABLED: Joi.boolean().truthy('true').falsy('false').default(true),
  FRONTEND_URL: Joi.string().uri().default('http://localhost:4200'),
  PAYSTACK_SECRET_KEY: Joi.string().required(),
  PAYSTACK_PUBLIC_KEY: Joi.string().required(),
  PAYSTACK_CURRENCY: Joi.string().default('GHS'),
  PAYSTACK_FEE_PERCENT: Joi.number().min(0).max(100).default(1.95),
  PAYSTACK_FEE_FLAT: Joi.number().min(0).default(0),
  PAYSTACK_FEE_CAP: Joi.number().min(0).empty('').allow(null).optional(),
  PAYSTACK_CALLBACK_URL: Joi.string().uri().allow('').optional(),
  PAYSTACK_CHANNELS: Joi.string().default('card,mobile_money,bank_transfer'),
  PII_ENCRYPTION_KEY: Joi.string().allow('').optional(),
  MAIL_FROM: Joi.string().default('PropFlow <noreply@propflow.app>'),
  SMTP_HOST: Joi.string().allow('').optional(),
  SMTP_PORT: Joi.number().port().default(587),
  SMTP_SECURE: Joi.boolean().truthy('true').falsy('false').default(false),
  SMTP_USER: Joi.string().allow('').optional(),
  SMTP_PASS: Joi.string().allow('').optional(),
  PLATFORM_ADMIN_EMAIL: Joi.string().email().default('platform@propflow.app'),
});
