import { DataTableColumn, DataTableFilter } from '../interfaces/data-table.interface';
import { CollectionPageConfig, DataCollection, FormField } from '../interfaces/data.interface';
import { badgeVariantFor } from '../utils';

const ACTIONS = {
  key: 'actions',
  header: '',
  type: 'actions' as const,
  widthClass: 'w-32',
  actions: [
    { id: 'view', label: 'View' },
    { id: 'edit', label: 'Edit' },
    { id: 'delete', label: 'Delete', tone: 'danger' as const },
  ],
};

const VIEW_DELETE = {
  key: 'actions',
  header: '',
  type: 'actions' as const,
  widthClass: 'w-28',
  actions: [
    { id: 'view', label: 'View' },
    { id: 'delete', label: 'Delete', tone: 'danger' as const },
  ],
};

const VIEW_ONLY = {
  key: 'actions',
  header: '',
  type: 'actions' as const,
  widthClass: 'w-20',
  actions: [{ id: 'view', label: 'View' }],
};

function badgeCol(key: string, header: string): DataTableColumn {
  return {
    key,
    header,
    type: 'badge',
    sortable: true,
    badgeVariant: (row) => badgeVariantFor(String((row as Record<string, unknown>)[key] ?? '')),
  };
}

export const COLLECTION_PAGES: Record<DataCollection, CollectionPageConfig> = {
  properties: {
    id: 'properties',
    path: 'properties',
    eyebrow: 'Portfolio',
    title: 'Properties',
    description: 'Buildings and blocks. Occupancy is calculated from active units.',
    createLabel: 'Add property',
    exportFileName: 'propflow-properties',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  units: {
    id: 'units',
    path: 'units',
    eyebrow: 'Portfolio',
    title: 'Units',
    description: 'Unit code, type, rent, and occupancy. Overlapping leases are blocked in the API.',
    createLabel: 'Add unit',
    exportFileName: 'propflow-units',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  tenants: {
    id: 'tenants',
    path: 'tenants',
    eyebrow: 'Leasing',
    title: 'Tenants',
    description: 'Profiles, KYC status, and contact details for occupants.',
    createLabel: 'Add tenant',
    exportFileName: 'propflow-tenants',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  leases: {
    id: 'leases',
    path: 'leases',
    eyebrow: 'Leasing',
    title: 'Leases',
    description: 'Create, renew, and terminate. One active lease per unit.',
    createLabel: 'Add lease',
    exportFileName: 'propflow-leases',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  invoices: {
    id: 'invoices',
    path: 'invoices',
    eyebrow: 'Collections',
    title: 'Invoices',
    description: 'Scheduled rent invoices with due, partial, and overdue states.',
    createLabel: 'Add invoice',
    exportFileName: 'propflow-invoices',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  payments: {
    id: 'payments',
    path: 'payments',
    eyebrow: 'Collections',
    title: 'Payments',
    description: 'Manual payment posting with method and reference.',
    createLabel: 'Post payment',
    exportFileName: 'propflow-payments',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  arrears: {
    id: 'arrears',
    path: 'arrears',
    eyebrow: 'Collections',
    title: 'Arrears console',
    description: 'Aging buckets with reminder actions.',
    createLabel: 'Add arrears record',
    exportFileName: 'propflow-arrears',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  tickets: {
    id: 'tickets',
    path: 'tickets',
    eyebrow: 'Maintenance',
    title: 'Work orders',
    description: 'Open → Assigned → In progress → Resolved → Closed, with SLA due times.',
    createLabel: 'Create ticket',
    exportFileName: 'propflow-tickets',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  documents: {
    id: 'documents',
    path: 'documents',
    eyebrow: 'Compliance',
    title: 'Document vault',
    description: 'Lease docs, IDs, and certificates with expiry highlighting.',
    createLabel: 'Add document',
    exportFileName: 'propflow-documents',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  notifications: {
    id: 'notifications',
    path: 'notifications',
    eyebrow: 'Inbox',
    title: 'Notifications',
    description: 'In-app alerts for arrears, expiry, and SLA.',
    createLabel: 'Add notification',
    exportFileName: 'propflow-notifications',
    canCreate: false,
    canEdit: false,
    canDelete: true,
  },
  'audit-logs': {
    id: 'audit-logs',
    path: 'audit-logs',
    eyebrow: 'Admin',
    title: 'Audit logs',
    description: 'Privileged actions with actor, entity, and IP. Owner only.',
    createLabel: 'Add log',
    exportFileName: 'propflow-audit-logs',
    canCreate: false,
    canEdit: false,
    canDelete: false,
  },
};

export const COLLECTION_COLUMNS: Record<DataCollection, DataTableColumn[]> = {
  properties: [
    { key: 'name', header: 'Property', sortable: true },
    { key: 'location', header: 'Location', sortable: true },
    { key: 'units', header: 'Units', sortable: true, align: 'right' },
    { key: 'occupancy', header: 'Occupancy', sortable: true },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  units: [
    { key: 'unitCode', header: 'Unit', sortable: true },
    { key: 'property', header: 'Property', sortable: true },
    { key: 'type', header: 'Type', sortable: true },
    { key: 'rent', header: 'Rent', sortable: true },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  tenants: [
    { key: 'fullName', header: 'Tenant', sortable: true },
    { key: 'email', header: 'Email' },
    { key: 'phone', header: 'Phone' },
    badgeCol('kycStatus', 'KYC'),
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  leases: [
    { key: 'id', header: 'Lease', sortable: true },
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'unit', header: 'Unit', sortable: true },
    { key: 'startDate', header: 'Start', type: 'date', sortable: true },
    { key: 'endDate', header: 'End', type: 'date', sortable: true },
    { key: 'rent', header: 'Rent' },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  invoices: [
    { key: 'id', header: 'Invoice', sortable: true },
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'period', header: 'Period' },
    { key: 'dueDate', header: 'Due', type: 'date', sortable: true },
    { key: 'amount', header: 'Amount' },
    { key: 'balance', header: 'Balance' },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  payments: [
    { key: 'id', header: 'Payment', sortable: true },
    { key: 'invoiceId', header: 'Invoice' },
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'amount', header: 'Amount' },
    { key: 'method', header: 'Method' },
    { key: 'reference', header: 'Reference' },
    { key: 'paidAt', header: 'Paid at', type: 'date', sortable: true },
    ACTIONS,
  ],
  arrears: [
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'lease', header: 'Lease' },
    { key: 'bucket', header: 'Bucket' },
    { key: 'balance', header: 'Balance' },
    { key: 'lastReminder', header: 'Last reminder', type: 'date' },
    ACTIONS,
  ],
  tickets: [
    { key: 'id', header: 'Ticket', sortable: true },
    { key: 'unit', header: 'Unit', sortable: true },
    { key: 'category', header: 'Category' },
    badgeCol('priority', 'Priority'),
    { key: 'assignee', header: 'Assignee' },
    badgeCol('status', 'Status'),
    { key: 'slaDue', header: 'SLA due' },
    ACTIONS,
  ],
  documents: [
    { key: 'id', header: 'Document', sortable: true },
    { key: 'entity', header: 'Entity', sortable: true },
    { key: 'type', header: 'Type' },
    { key: 'expiresAt', header: 'Expires', type: 'date', sortable: true },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  notifications: [
    { key: 'title', header: 'Title', sortable: true },
    { key: 'message', header: 'Message' },
    { key: 'type', header: 'Type' },
    { key: 'createdAt', header: 'When' },
    VIEW_DELETE,
  ],
  'audit-logs': [
    { key: 'actor', header: 'Actor', sortable: true },
    { key: 'action', header: 'Action' },
    { key: 'entity', header: 'Entity' },
    { key: 'ip', header: 'IP' },
    { key: 'createdAt', header: 'When', sortable: true },
    VIEW_ONLY,
  ],
};

export const COLLECTION_FILTERS: Record<DataCollection, DataTableFilter[]> = {
  properties: [{ key: 'status', label: 'Status', options: [{ label: 'Active', value: 'active' }] }],
  units: [
    {
      key: 'status',
      label: 'Status',
      options: [
        { label: 'Occupied', value: 'occupied' },
        { label: 'Vacant', value: 'vacant' },
        { label: 'Maintenance', value: 'maintenance' },
      ],
    },
  ],
  tenants: [
    {
      key: 'kycStatus',
      label: 'KYC',
      options: [
        { label: 'Verified', value: 'verified' },
        { label: 'Pending', value: 'pending' },
      ],
    },
  ],
  leases: [{ key: 'status', label: 'Status', options: [{ label: 'Active', value: 'active' }, { label: 'Ending', value: 'ending' }] }],
  invoices: [
    {
      key: 'status',
      label: 'Status',
      options: [
        { label: 'Paid', value: 'paid' },
        { label: 'Partial', value: 'partial' },
        { label: 'Overdue', value: 'overdue' },
      ],
    },
  ],
  payments: [
    {
      key: 'method',
      label: 'Method',
      options: [
        { label: 'Bank transfer', value: 'bank_transfer' },
        { label: 'Mobile money', value: 'mobile_money' },
      ],
    },
  ],
  arrears: [
    {
      key: 'bucket',
      label: 'Bucket',
      options: [
        { label: '1-30 days', value: '1-30 days' },
        { label: '31-60 days', value: '31-60 days' },
        { label: '61-90 days', value: '61-90 days' },
      ],
    },
  ],
  tickets: [
    {
      key: 'status',
      label: 'Status',
      options: [
        { label: 'Open', value: 'open' },
        { label: 'Assigned', value: 'assigned' },
        { label: 'In progress', value: 'in_progress' },
      ],
    },
    {
      key: 'priority',
      label: 'Priority',
      options: [
        { label: 'High', value: 'high' },
        { label: 'Medium', value: 'medium' },
        { label: 'Low', value: 'low' },
      ],
    },
  ],
  documents: [
    {
      key: 'status',
      label: 'Status',
      options: [
        { label: 'Valid', value: 'valid' },
        { label: 'Expiring', value: 'expiring' },
      ],
    },
  ],
  notifications: [{ key: 'type', label: 'Type', options: [{ label: 'Arrears', value: 'arrears' }, { label: 'Compliance', value: 'compliance' }, { label: 'Maintenance', value: 'maintenance' }] }],
  'audit-logs': [],
};

export const COLLECTION_FIELDS: Record<DataCollection, FormField[]> = {
  properties: [
    { key: 'name', label: 'Property name', type: 'text', required: true },
    { key: 'location', label: 'Location', type: 'text', required: true },
    { key: 'units', label: 'Units', type: 'number', required: true },
    { key: 'occupancy', label: 'Occupancy', type: 'text', placeholder: '92%' },
    { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] },
  ],
  units: [
    { key: 'unitCode', label: 'Unit code', type: 'text', required: true },
    { key: 'property', label: 'Property', type: 'text', required: true },
    { key: 'type', label: 'Type', type: 'select', options: [{ label: 'Studio', value: 'studio' }, { label: '1 bed', value: '1 bed' }, { label: '2 bed', value: '2 bed' }, { label: '3 bed', value: '3 bed' }] },
    { key: 'rent', label: 'Rent', type: 'text', required: true, placeholder: 'GHS 2,500' },
    { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Occupied', value: 'occupied' }, { label: 'Vacant', value: 'vacant' }, { label: 'Maintenance', value: 'maintenance' }] },
  ],
  tenants: [
    { key: 'fullName', label: 'Full name', type: 'text', required: true },
    { key: 'email', label: 'Email', type: 'email', required: true },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'kycStatus', label: 'KYC', type: 'select', options: [{ label: 'Verified', value: 'verified' }, { label: 'Pending', value: 'pending' }] },
    { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] },
  ],
  leases: [
    { key: 'tenant', label: 'Tenant', type: 'text', required: true },
    { key: 'unit', label: 'Unit', type: 'text', required: true },
    { key: 'startDate', label: 'Start date', type: 'date', required: true },
    { key: 'endDate', label: 'End date', type: 'date', required: true },
    { key: 'rent', label: 'Rent', type: 'text', required: true },
    { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Active', value: 'active' }, { label: 'Ending', value: 'ending' }, { label: 'Terminated', value: 'terminated' }] },
  ],
  invoices: [
    { key: 'tenant', label: 'Tenant', type: 'text', required: true },
    { key: 'period', label: 'Period', type: 'text', required: true },
    { key: 'dueDate', label: 'Due date', type: 'date', required: true },
    { key: 'amount', label: 'Amount', type: 'text', required: true },
    { key: 'balance', label: 'Balance', type: 'text', required: true },
    { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Paid', value: 'paid' }, { label: 'Partial', value: 'partial' }, { label: 'Overdue', value: 'overdue' }] },
  ],
  payments: [
    { key: 'invoiceId', label: 'Invoice ID', type: 'text', required: true },
    { key: 'tenant', label: 'Tenant', type: 'text', required: true },
    { key: 'amount', label: 'Amount', type: 'text', required: true },
    { key: 'method', label: 'Method', type: 'select', options: [{ label: 'Bank transfer', value: 'bank_transfer' }, { label: 'Mobile money', value: 'mobile_money' }, { label: 'Cash', value: 'cash' }] },
    { key: 'reference', label: 'Reference', type: 'text' },
    { key: 'paidAt', label: 'Paid at', type: 'date', required: true },
  ],
  arrears: [
    { key: 'tenant', label: 'Tenant', type: 'text', required: true },
    { key: 'lease', label: 'Lease', type: 'text', required: true },
    { key: 'bucket', label: 'Bucket', type: 'select', options: [{ label: '1-30 days', value: '1-30 days' }, { label: '31-60 days', value: '31-60 days' }, { label: '61-90 days', value: '61-90 days' }] },
    { key: 'balance', label: 'Balance', type: 'text', required: true },
    { key: 'lastReminder', label: 'Last reminder', type: 'date' },
  ],
  tickets: [
    { key: 'unit', label: 'Unit', type: 'text', required: true },
    { key: 'category', label: 'Category', type: 'select', options: [{ label: 'Plumbing', value: 'plumbing' }, { label: 'Electrical', value: 'electrical' }, { label: 'HVAC', value: 'hvac' }, { label: 'Other', value: 'other' }] },
    { key: 'priority', label: 'Priority', type: 'select', options: [{ label: 'High', value: 'high' }, { label: 'Medium', value: 'medium' }, { label: 'Low', value: 'low' }] },
    { key: 'assignee', label: 'Assignee', type: 'text' },
    { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Open', value: 'open' }, { label: 'Assigned', value: 'assigned' }, { label: 'In progress', value: 'in_progress' }, { label: 'Resolved', value: 'resolved' }, { label: 'Closed', value: 'closed' }] },
    { key: 'slaDue', label: 'SLA due', type: 'text' },
  ],
  documents: [
    { key: 'entity', label: 'Entity', type: 'text', required: true },
    { key: 'type', label: 'Document type', type: 'text', required: true },
    { key: 'expiresAt', label: 'Expires', type: 'date' },
    { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Valid', value: 'valid' }, { label: 'Expiring', value: 'expiring' }, { label: 'Expired', value: 'expired' }] },
  ],
  notifications: [],
  'audit-logs': [],
};
