import { DataTableColumn, DataTableFilter } from '../interfaces/data-table.interface';
import { CollectionPageConfig, FormField, FormFieldOption, FormFieldOptionsFrom } from '../interfaces/data.interface';
import { badgeVariantFor } from '../utils';
import {
  ARREARS_BUCKET_LABELS,
  ArrearsBucket,
  COMPANY_USER_ROLES,
  DOCUMENT_TYPE_LABELS,
  DataCollection,
  DocumentStatus,
  EntityType,
  InvoiceStatus,
  KycStatus,
  LeaseStatus,
  NotificationKind,
  OrgStatus,
  PAYMENT_METHOD_LABELS,
  PaymentMethod,
  RecordStatus,
  TICKET_CATEGORY_LABELS,
  TICKET_STATUS_LABELS,
  TicketCategory,
  TicketPriority,
  TicketStatus,
  UNIT_TYPE_LABELS,
  USER_ROLE_LABELS,
  UnitStatus,
  UnitType,
  VAULT_DOCUMENT_TYPES,
  enumOptions,
  pickOptions,
} from '../enums';

const ACTIONS = {
  key: 'actions',
  header: '',
  type: 'actions' as const,
  widthClass: 'w-32',
  actions: [
    { id: 'view', label: 'View' },
    { id: 'edit', label: 'Edit' },
    { id: 'delete', label: 'Delete', tone: 'danger' as const },
  ],
};

const VIEW_DELETE = {
  key: 'actions',
  header: '',
  type: 'actions' as const,
  widthClass: 'w-28',
  actions: [
    { id: 'view', label: 'View' },
    { id: 'delete', label: 'Delete', tone: 'danger' as const },
  ],
};

const VIEW_ONLY = {
  key: 'actions',
  header: '',
  type: 'actions' as const,
  widthClass: 'w-20',
  actions: [{ id: 'view', label: 'View' }],
};

function badgeCol(key: string, header: string): DataTableColumn {
  return {
    key,
    header,
    type: 'badge',
    sortable: true,
    badgeVariant: (row) => badgeVariantFor(String((row as Record<string, unknown>)[key] ?? '')),
  };
}

function selectOpts<T extends string>(values: readonly T[], labels?: Partial<Record<T, string>>): FormFieldOption[] {
  return pickOptions(values, labels);
}

function from(
  collection: DataCollection,
  labelKey: string,
  extras: Pick<FormFieldOptionsFrom, 'valueKey' | 'hint'> = {},
): FormFieldOptionsFrom {
  return { collection, labelKey, ...extras };
}

export const COLLECTION_PAGES: Record<DataCollection, CollectionPageConfig> = {
  [DataCollection.Properties]: {
    id: DataCollection.Properties,
    path: DataCollection.Properties,
    eyebrow: 'Portfolio',
    title: 'Properties',
    description: 'Buildings and blocks. Occupancy is calculated from active units.',
    createLabel: 'Add property',
    exportFileName: 'propflow-properties',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Units]: {
    id: DataCollection.Units,
    path: DataCollection.Units,
    eyebrow: 'Portfolio',
    title: 'Units',
    description: 'Unit code, type, rent, and occupancy. Overlapping leases are blocked in the API.',
    createLabel: 'Add unit',
    exportFileName: 'propflow-units',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Tenants]: {
    id: DataCollection.Tenants,
    path: DataCollection.Tenants,
    eyebrow: 'Leasing',
    title: 'Tenants',
    description: 'Profiles, KYC status, and contact details for occupants.',
    createLabel: 'Add tenant',
    exportFileName: 'propflow-tenants',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Leases]: {
    id: DataCollection.Leases,
    path: DataCollection.Leases,
    eyebrow: 'Leasing',
    title: 'Leases',
    description: 'Create, renew, and terminate. One active lease per unit.',
    createLabel: 'Add lease',
    exportFileName: 'propflow-leases',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Invoices]: {
    id: DataCollection.Invoices,
    path: DataCollection.Invoices,
    eyebrow: 'Collections',
    title: 'Invoices',
    description: 'Scheduled rent invoices with due, partial, and overdue states.',
    createLabel: 'Add invoice',
    exportFileName: 'propflow-invoices',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Payments]: {
    id: DataCollection.Payments,
    path: DataCollection.Payments,
    eyebrow: 'Collections',
    title: 'Payments',
    description: 'Manual payment posting with method and reference.',
    createLabel: 'Post payment',
    exportFileName: 'propflow-payments',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Arrears]: {
    id: DataCollection.Arrears,
    path: DataCollection.Arrears,
    eyebrow: 'Collections',
    title: 'Arrears console',
    description: 'Aging buckets with reminder actions.',
    createLabel: 'Add arrears record',
    exportFileName: 'propflow-arrears',
    canCreate: false,
    canEdit: false,
    canDelete: false,
  },
  [DataCollection.Tickets]: {
    id: DataCollection.Tickets,
    path: DataCollection.Tickets,
    eyebrow: 'Maintenance',
    title: 'Work orders',
    description: 'Open → Assigned → In progress → Resolved → Closed, with SLA due times.',
    createLabel: 'Create ticket',
    exportFileName: 'propflow-tickets',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Documents]: {
    id: DataCollection.Documents,
    path: DataCollection.Documents,
    eyebrow: 'Compliance',
    title: 'Document vault',
    description: 'Lease docs, IDs, certificates, and generated agreements. Owners can preview and download forms filled from the tenant file.',
    createLabel: 'Add document',
    exportFileName: 'propflow-documents',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  [DataCollection.Notifications]: {
    id: DataCollection.Notifications,
    path: DataCollection.Notifications,
    eyebrow: 'Inbox',
    title: 'Notifications',
    description: 'In-app alerts for arrears, expiry, and SLA.',
    createLabel: 'Add notification',
    exportFileName: 'propflow-notifications',
    canCreate: false,
    canEdit: false,
    canDelete: true,
  },
  [DataCollection.AuditLogs]: {
    id: DataCollection.AuditLogs,
    path: DataCollection.AuditLogs,
    eyebrow: 'Admin',
    title: 'Audit logs',
    description: 'Privileged actions with actor, entity, and IP. Owner only.',
    createLabel: 'Add log',
    exportFileName: 'propflow-audit-logs',
    canCreate: false,
    canEdit: false,
    canDelete: false,
  },
  [DataCollection.Users]: {
    id: DataCollection.Users,
    path: DataCollection.Users,
    eyebrow: 'Admin',
    title: 'Users',
    description: 'Invite owners, managers, finance, vendors, and tenants to this company.',
    createLabel: 'Add user',
    exportFileName: 'propflow-users',
    canCreate: true,
    canEdit: true,
    canDelete: false,
  },
  [DataCollection.Organizations]: {
    id: DataCollection.Organizations,
    path: DataCollection.Organizations,
    eyebrow: 'Platform',
    title: 'Companies',
    description: 'Real-estate operators on PropFlow. A temporary owner password is generated and emailed; they must finish onboarding before the workspace unlocks.',
    createLabel: 'Add company',
    exportFileName: 'propflow-organizations',
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
};

export const COLLECTION_COLUMNS: Record<DataCollection, DataTableColumn[]> = {
  properties: [
    { key: 'name', header: 'Property', sortable: true },
    { key: 'location', header: 'Location', sortable: true },
    { key: 'units', header: 'Units', sortable: true, align: 'right' },
    { key: 'occupancy', header: 'Occupancy', sortable: true },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  units: [
    { key: 'unitCode', header: 'Unit', sortable: true },
    { key: 'property', header: 'Property', sortable: true },
    { key: 'type', header: 'Type', sortable: true },
    { key: 'rent', header: 'Rent', sortable: true },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  tenants: [
    { key: 'fullName', header: 'Tenant', sortable: true },
    { key: 'email', header: 'Email' },
    { key: 'phone', header: 'Phone' },
    badgeCol('kycStatus', 'KYC'),
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  leases: [
    { key: 'id', header: 'Lease', sortable: true },
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'unit', header: 'Unit', sortable: true },
    { key: 'startDate', header: 'Start', type: 'date', sortable: true },
    { key: 'endDate', header: 'End', type: 'date', sortable: true },
    { key: 'rent', header: 'Rent' },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  invoices: [
    { key: 'id', header: 'Invoice', sortable: true },
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'period', header: 'Period' },
    { key: 'dueDate', header: 'Due', type: 'date', sortable: true },
    { key: 'amount', header: 'Amount' },
    { key: 'balance', header: 'Balance' },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  payments: [
    { key: 'id', header: 'Payment', sortable: true },
    { key: 'invoiceId', header: 'Invoice' },
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'amount', header: 'Amount' },
    { key: 'method', header: 'Method' },
    { key: 'reference', header: 'Reference' },
    { key: 'paidAt', header: 'Paid at', type: 'date', sortable: true },
    ACTIONS,
  ],
  arrears: [
    { key: 'tenant', header: 'Tenant', sortable: true },
    { key: 'lease', header: 'Lease' },
    { key: 'bucket', header: 'Bucket' },
    { key: 'balance', header: 'Balance' },
    { key: 'lastReminder', header: 'Last reminder', type: 'date' },
    ACTIONS,
  ],
  tickets: [
    { key: 'id', header: 'Ticket', sortable: true },
    { key: 'unit', header: 'Unit', sortable: true },
    { key: 'category', header: 'Category' },
    badgeCol('priority', 'Priority'),
    { key: 'assignee', header: 'Assignee' },
    badgeCol('status', 'Status'),
    { key: 'slaDue', header: 'SLA due' },
    ACTIONS,
  ],
  documents: [
    { key: 'id', header: 'Document', sortable: true },
    { key: 'entity', header: 'Entity', sortable: true },
    { key: 'type', header: 'Type' },
    { key: 'expiresAt', header: 'Expires', type: 'date', sortable: true },
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  notifications: [
    { key: 'title', header: 'Title', sortable: true },
    { key: 'message', header: 'Message' },
    { key: 'type', header: 'Type' },
    { key: 'createdAt', header: 'When' },
    VIEW_DELETE,
  ],
  'audit-logs': [
    { key: 'actor', header: 'Actor', sortable: true },
    { key: 'action', header: 'Action' },
    { key: 'entity', header: 'Entity' },
    { key: 'ip', header: 'IP' },
    { key: 'createdAt', header: 'When', sortable: true },
    VIEW_ONLY,
  ],
  users: [
    { key: 'fullName', header: 'Name', sortable: true },
    { key: 'email', header: 'Email' },
    badgeCol('role', 'Role'),
    badgeCol('status', 'Status'),
    ACTIONS,
  ],
  organizations: [
    { key: 'name', header: 'Company', sortable: true },
    { key: 'users', header: 'Users', align: 'right' },
    { key: 'properties', header: 'Properties', align: 'right' },
    badgeCol('status', 'Status'),
    badgeCol('onboarding', 'Onboarding'),
    ACTIONS,
  ],
};

export const COLLECTION_FILTERS: Record<DataCollection, DataTableFilter[]> = {
  [DataCollection.Properties]: [{ key: 'status', label: 'Status', options: selectOpts([RecordStatus.Active]) }],
  [DataCollection.Units]: [{ key: 'status', label: 'Status', options: enumOptions(UnitStatus) }],
  [DataCollection.Tenants]: [{ key: 'kycStatus', label: 'KYC', options: enumOptions(KycStatus) }],
  [DataCollection.Leases]: [
    { key: 'status', label: 'Status', options: selectOpts([LeaseStatus.Active, LeaseStatus.Ending]) },
  ],
  [DataCollection.Invoices]: [
    {
      key: 'status',
      label: 'Status',
      options: selectOpts([InvoiceStatus.Paid, InvoiceStatus.Partial, InvoiceStatus.Overdue]),
    },
  ],
  [DataCollection.Payments]: [
    {
      key: 'method',
      label: 'Method',
      options: selectOpts([PaymentMethod.BankTransfer, PaymentMethod.MobileMoney], PAYMENT_METHOD_LABELS),
    },
  ],
  [DataCollection.Arrears]: [
    {
      key: 'bucket',
      label: 'Bucket',
      options: selectOpts(
        [ArrearsBucket.Days1To30, ArrearsBucket.Days31To60, ArrearsBucket.Days61To90],
        ARREARS_BUCKET_LABELS,
      ),
    },
  ],
  [DataCollection.Tickets]: [
    {
      key: 'status',
      label: 'Status',
      options: selectOpts(
        [TicketStatus.Open, TicketStatus.Assigned, TicketStatus.InProgress],
        TICKET_STATUS_LABELS,
      ),
    },
    { key: 'priority', label: 'Priority', options: enumOptions(TicketPriority) },
  ],
  [DataCollection.Documents]: [
    { key: 'type', label: 'Type', options: selectOpts(VAULT_DOCUMENT_TYPES, DOCUMENT_TYPE_LABELS) },
    { key: 'status', label: 'Status', options: enumOptions(DocumentStatus) },
  ],
  [DataCollection.Notifications]: [{ key: 'type', label: 'Type', options: enumOptions(NotificationKind) }],
  [DataCollection.AuditLogs]: [],
  [DataCollection.Users]: [{ key: 'role', label: 'Role', options: selectOpts(COMPANY_USER_ROLES, USER_ROLE_LABELS) }],
  [DataCollection.Organizations]: [{ key: 'status', label: 'Status', options: enumOptions(OrgStatus) }],
};

export const COLLECTION_FIELDS: Record<DataCollection, FormField[]> = {
  [DataCollection.Properties]: [
    { key: 'name', label: 'Property name', type: 'text', required: true },
    { key: 'location', label: 'Location', type: 'text', required: true },
    { key: 'status', label: 'Status', type: 'select', options: enumOptions(RecordStatus) },
  ],
  [DataCollection.Units]: [
    { key: 'unitCode', label: 'Unit code', type: 'text', required: true },
    {
      key: 'propertyId',
      label: 'Property',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Properties, 'name', { valueKey: 'id' }),
    },
    { key: 'type', label: 'Unit type', type: 'select', options: enumOptions(UnitType, UNIT_TYPE_LABELS) },
    { key: 'rentAmount', label: 'Rent (GHS)', type: 'number', required: true, placeholder: '2500' },
    { key: 'status', label: 'Status', type: 'select', options: enumOptions(UnitStatus) },
  ],
  [DataCollection.Tenants]: [
    { key: 'fullName', label: 'Full name', type: 'text', required: true },
    { key: 'email', label: 'Email', type: 'email', required: true },
    { key: 'phone', label: 'Phone', type: 'tel', placeholder: '+233 24 000 0000' },
    { key: 'kycStatus', label: 'KYC', type: 'select', options: enumOptions(KycStatus) },
    { key: 'status', label: 'Status', type: 'select', options: enumOptions(RecordStatus) },
  ],
  [DataCollection.Leases]: [
    {
      key: 'tenantId',
      label: 'Tenant',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Tenants, 'fullName', { valueKey: 'id' }),
    },
    {
      key: 'unitId',
      label: 'Unit',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Units, 'unitCode', { valueKey: 'id' }),
    },
    { key: 'startDate', label: 'Start date', type: 'date', required: true },
    { key: 'endDate', label: 'End date', type: 'date', required: true },
    { key: 'rentAmount', label: 'Rent (GHS)', type: 'number', required: true, placeholder: '2500' },
    { key: 'dueDay', label: 'Due day', type: 'number', required: true, placeholder: '5' },
    { key: 'status', label: 'Status', type: 'select', options: enumOptions(LeaseStatus) },
  ],
  [DataCollection.Invoices]: [
    {
      key: 'leaseId',
      label: 'Lease',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Leases, 'id', { valueKey: 'id' }),
    },
    { key: 'periodStart', label: 'Period start', type: 'date', required: true },
    { key: 'periodEnd', label: 'Period end', type: 'date', required: true },
    { key: 'dueDate', label: 'Due date', type: 'date', required: true },
    { key: 'amount', label: 'Amount (GHS)', type: 'number', required: true, placeholder: '2500' },
  ],
  [DataCollection.Payments]: [
    {
      key: 'invoiceId',
      label: 'Invoice',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Invoices, 'id'),
    },
    { key: 'amount', label: 'Amount (GHS)', type: 'number', required: true, placeholder: '2500' },
    {
      key: 'method',
      label: 'Method',
      type: 'select',
      options: enumOptions(PaymentMethod, PAYMENT_METHOD_LABELS),
    },
    { key: 'reference', label: 'Reference', type: 'text', placeholder: 'MM-10422' },
    { key: 'paidAt', label: 'Paid at', type: 'date', required: true },
  ],
  [DataCollection.Arrears]: [
    {
      key: 'tenant',
      label: 'Tenant',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Tenants, 'fullName'),
    },
    {
      key: 'lease',
      label: 'Lease',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Leases, 'id'),
    },
    { key: 'bucket', label: 'Bucket', type: 'select', options: enumOptions(ArrearsBucket, ARREARS_BUCKET_LABELS) },
    { key: 'balance', label: 'Balance', type: 'text', required: true, placeholder: 'GHS 1,500' },
    { key: 'lastReminder', label: 'Last reminder', type: 'date' },
  ],
  [DataCollection.Tickets]: [
    {
      key: 'propertyId',
      label: 'Property',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: from(DataCollection.Properties, 'name', { valueKey: 'id' }),
    },
    {
      key: 'unitId',
      label: 'Unit',
      type: 'select',
      searchable: true,
      optionsFrom: from(DataCollection.Units, 'unitCode', { valueKey: 'id' }),
    },
    { key: 'category', label: 'Category', type: 'select', options: enumOptions(TicketCategory, TICKET_CATEGORY_LABELS) },
    { key: 'priority', label: 'Priority', type: 'select', options: enumOptions(TicketPriority) },
    { key: 'status', label: 'Status', type: 'select', options: enumOptions(TicketStatus, TICKET_STATUS_LABELS) },
    {
      key: 'notes',
      label: 'Notes',
      type: 'textarea',
      rows: 4,
      placeholder: 'Describe the issue, access notes, or completion comments.',
    },
  ],
  [DataCollection.Documents]: [
    { key: 'entityType', label: 'Entity type', type: 'select', required: true, options: enumOptions(EntityType) },
    {
      key: 'entityId',
      label: 'Entity',
      type: 'select',
      required: true,
      searchable: true,
      optionsFrom: [
        from(DataCollection.Properties, 'name', { valueKey: 'id', hint: 'Property' }),
        from(DataCollection.Tenants, 'fullName', { valueKey: 'id', hint: 'Tenant' }),
        from(DataCollection.Units, 'unitCode', { valueKey: 'id', hint: 'Unit' }),
        from(DataCollection.Leases, 'id', { valueKey: 'id', hint: 'Lease' }),
      ],
    },
    {
      key: 'type',
      label: 'Document type',
      type: 'select',
      required: true,
      options: selectOpts(VAULT_DOCUMENT_TYPES, DOCUMENT_TYPE_LABELS),
    },
    { key: 'expiresAt', label: 'Expires', type: 'date' },
    { key: 'fileUrl', label: 'File URL', type: 'text', placeholder: 'https://…' },
    { key: 'status', label: 'Status', type: 'select', options: enumOptions(DocumentStatus) },
  ],
  [DataCollection.Notifications]: [],
  [DataCollection.AuditLogs]: [],
  [DataCollection.Users]: [
    { key: 'fullName', label: 'Full name', type: 'text', required: true },
    { key: 'email', label: 'Email', type: 'email', required: true },
    {
      key: 'role',
      label: 'Role',
      type: 'select',
      required: true,
      options: selectOpts(COMPANY_USER_ROLES, USER_ROLE_LABELS),
    },
    { key: 'password', label: 'Temporary password', type: 'text', placeholder: 'Leave blank to generate' },
  ],
  [DataCollection.Organizations]: [
    { key: 'name', label: 'Company name', type: 'text', required: true },
    { key: 'ownerEmail', label: 'Owner email', type: 'email', required: true },
    { key: 'ownerFullName', label: 'Owner name', type: 'text', required: true },
    { key: 'phone', label: 'Company phone', type: 'text' },
    { key: 'address', label: 'Address', type: 'text' },
    { key: 'city', label: 'City', type: 'text' },
  ],
};
